//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Questions()
        {
            this.AnswerChoices = new HashSet<AnswerChoices>();
        }
    
        public int QuestionId { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public int LevelId { get; set; }
        public int CategoryId { get; set; }
        public int SubCategoryId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswerChoices> AnswerChoices { get; set; }
        public virtual Categories Categories { get; set; }
        public virtual QuestionLevels QuestionLevels { get; set; }
        public virtual SubCategories SubCategories { get; set; }
    }
}
